baseurl = "/"
title = "ADL publicsectR"
theme = "ghostwriter"
languageCode = "en-uk"
copyright = "Kristen Osborne"
disqusShortname = "XXX"
googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Public SectR Adelaide"
    description = "A group for R programmers of all experience levels in the public sector, South Australia"
    github = "https://github.com/KOsb/ADL-publicsectR"
   # gitlab = "https://gitlab.com/XXX"
  #  linkedin = "https://linkedin.com/in/XXX/"
  #  gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/PublicSectRAdl"
   # stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
   # email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"
    
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
    
[[menu.main]]
    name = "Resources"
    url = "/page/resources/"
    weight = 5

